### ISSUE TITLE
Python 3.5 Compatibility. HTMLParser strict arugment is removed.

### ISSUE THREAD

**Issue by Ecno92** [necaris/python3-openid#16]
While adding test support for Python 3.5 in Django Allauth (https://github.com/pennersr/django-allauth/pull/1185) I discovered a bug in this project.

When I'm testing Django Allauth against Python 3.5 I get the following error output:

```
ERROR: test_discovery_failure (allauth.socialaccount.providers.openid.tests.OpenIDTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pennersr/django-allauth/allauth/socialaccount/providers/openid/tests.py", line 25, in test_discovery_failure

    dict(openid='http://www.google.com'))

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/test/client.py", line 512, in post

    secure=secure, **extra)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/test/client.py", line 313, in post

    secure=secure, **extra)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/test/client.py", line 379, in generic

    return self.request(**r)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/test/client.py", line 466, in request

    six.reraise(*exc_info)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/utils/six.py", line 659, in reraise

    raise value

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/django/core/handlers/base.py", line 132, in get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/travis/build/pennersr/django-allauth/allauth/socialaccount/providers/openid/views.py", line 38, in login

    auth_request = client.begin(form.cleaned_data['openid'])

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/consumer/consumer.py", line 343, in begin

    service = disco.getNextService(self._discover)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/yadis/manager.py", line 105, in getNextService

    yadis_url, services = discover(self.url)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/consumer/discover.py", line 471, in discover

    return discoverURI(identifier)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/consumer/discover.py", line 463, in discoverURI

    claimed_id, openid_services = discoverYadis(uri)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/consumer/discover.py", line 390, in discoverYadis

    response = yadisDiscover(uri)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/yadis/discover.py", line 85, in discover

    result.xrds_uri = whereIsYadis(resp)

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/yadis/discover.py", line 161, in whereIsYadis

    yadis_loc = findHTMLMeta(StringIO(content))

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/yadis/parsehtml.py", line 178, in findHTMLMeta

    parser = YadisHTMLParser()

  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/openid/yadis/parsehtml.py", line 99, in __init__

    super(YadisHTMLParser, self).__init__(strict=False)

TypeError: __init__() got an unexpected keyword argument 'strict'
```
*from: https://travis-ci.org/pennersr/django-allauth/jobs/89955820*

The error is there because it calls a super with `__init__(strict=False)`. The strict argument of the HTMLParser is removed in Python 3.5. The parser now accepts and parses invalid input too. 
See https://docs.python.org/3.4/library/html.parser.html for more information. 

I'm not familiar with this code base of this project. So unfortunately I will not start working on a patch for this. Hopefully someone can fix this so we can enable testing against Python 3.5 in the Django Allauth project.

**Comment by necaris** [comment]
@Ecno92 This should be resolved in the new version `3.0.8` which is now published to PyPI
