### ISSUE TITLE
No module named `psycopg2` or `psycopg2cffi`

### ISSUE THREAD

**Issue by earthday** [necaris/python3-openid#46]
```
$ docker run --rm -ti python:alpine sh                                                                                                                               ‹ruby-2.3.1›
/ # python -V
Python 3.8.0
/ # python -m pip install python3-openid
Collecting python3-openid
  Downloading https://files.pythonhosted.org/packages/bd/de/52c5699f52dcee3037db587196dcaf63ffedf5fbeba3183afe9b21a3a89f/python3_openid-3.1.0-py3-none-any.whl (130kB)
     |████████████████████████████████| 133kB 352kB/s
Collecting defusedxml
  Downloading https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl
Installing collected packages: defusedxml, python3-openid
Successfully installed defusedxml-0.6.0 python3-openid-3.1.0
/ # python
Python 3.8.0 (default, Nov 15 2019, 02:22:06)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from openid.store.sqlstore import MySQLStore
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/openid/store/sqlstore.py", line 14, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/openid/store/sqlstore.py", line 16, in <module>
    from psycopg2cffi import compat
ModuleNotFoundError: No module named 'psycopg2cffi'
>>>
```

**Comment by earthday** [comment]
I only need MySQLStore, why I need `psycopg2` or `psycopg2cffi`?
https://github.com/necaris/python3-openid/blob/4911bbc196dfd6f9eda7155df9903d668720ecbf/openid/store/sqlstore.py#L13-L17

**Comment by earthday** [comment]
Find a workaround way to resolve this issue.
```
yum install -y postgresql-devel
python3 -m pip install psycopg2cffi
```

**Comment by bkmgit** [comment]
It would be helpful to use Sqlite for initial development and testing.
