### ISSUE TITLE
XML and bytestrings issue

### ISSUE THREAD

**Issue by maksbotan** [necaris/python3-openid#8]
Hi,
I get this traceback when i run `python-social-auth` django example:
```pytb
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../../social/apps/django_app/utils.py", line 45, in wrapper
    return func(request, backend, *args, **kwargs)
  File "../../social/apps/django_app/views.py", line 12, in auth
    return do_auth(request.social_strategy, redirect_name=REDIRECT_FIELD_NAME)
  File "../../social/actions.py", line 25, in do_auth
    return strategy.start()
  File "../../social/strategies/base.py", line 65, in start
    if self.backend.uses_redirect():
  File "../../social/backends/open_id.py", line 230, in uses_redirect
    return self.openid_request().shouldSendRedirect()
  File "../../social/backends/open_id.py", line 236, in openid_request
    params))
  File "/usr/lib64/python3.3/site-packages/openid/consumer/consumer.py", line 343, in begin
    service = disco.getNextService(self._discover)
  File "/usr/lib64/python3.3/site-packages/openid/yadis/manager.py", line 105, in getNextService
    yadis_url, services = discover(self.url)
  File "/usr/lib64/python3.3/site-packages/openid/consumer/discover.py", line 471, in discover
    return discoverURI(identifier)
  File "/usr/lib64/python3.3/site-packages/openid/consumer/discover.py", line 463, in discoverURI
    claimed_id, openid_services = discoverYadis(uri)
  File "/usr/lib64/python3.3/site-packages/openid/consumer/discover.py", line 395, in discoverYadis
    openid_services = OpenIDServiceEndpoint.fromXRDS(yadis_url, body)
  File "/usr/lib64/python3.3/site-packages/openid/consumer/discover.py", line 195, in fromXRDS
    return extractServices(uri, xrds, cls)
  File "/usr/lib64/python3.3/site-packages/openid/yadis/services.py", line 47, in applyFilter
    et = parseXRDS(xrd_data)
  File "/usr/lib64/python3.3/site-packages/openid/yadis/etxrd.py", line 69, in parseXRDS
    element = ElementTree.XML(text)
  File "lxml.etree.pyx", line 3012, in lxml.etree.XML (src/lxml/lxml.etree.c:67876)
  File "parser.pxi", line 1781, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102435)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```

This appears to be not fixed by PR #7, although tests pass indeed. Please check it and fix.

**Comment by necaris** [comment]
Unable to replicate this.
